### ISSUE TITLE
Instructions for Windows

### ISSUE THREAD

**Issue by littleli** [raspasov/cljs-101#1]
On Windows there is some escaping fun (again).
This shows both the failed instructions from README and later the successful invocation:

```sh
~ $ clj -Sdeps '{:deps {org.clojure/clojurescript {:mvn/version "RELEASE"}}}' -M -m cljs.repl.node
Error building classpath. class clojure.lang.Symbol cannot be cast to class java.lang.CharSequence (clojure.lang.Symbol is in unnamed module of loader 'app'; java.lang.CharSequence is in module java.base of loader 'bootstrap')
java.lang.ClassCastException: class clojure.lang.Symbol cannot be cast to class java.lang.CharSequence (clojure.lang.Symbol is in unnamed module of loader 'app'; java.lang.CharSequence is in module java.base of loader 'bootstrap')
        at clojure.core$re_matcher.invokeStatic(core.clj:4838)
        at clojure.core$re_find.invokeStatic(core.clj:4887)
        at clojure.core$re_find.invoke(core.clj:4887)
        at clojure.tools.deps.alpha.util.maven$version_range_QMARK_.invokeStatic(maven.clj:252)
        at clojure.tools.deps.alpha.util.maven$version_range_QMARK_.invoke(maven.clj:250)
        at clojure.tools.deps.alpha.extensions.maven$eval1016$fn__1019.invoke(maven.clj:47)
        at clojure.lang.MultiFn.invoke(MultiFn.java:239)
        at clojure.tools.deps.alpha$canonicalize_deps$fn__766.invoke(alpha.clj:363)
        at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
        at clojure.core.protocols$fn__8162.invokeStatic(protocols.clj:75)
        at clojure.core.protocols$fn__8162.invoke(protocols.clj:75)
        at clojure.core.protocols$fn__8110$G__8105__8123.invoke(protocols.clj:13)
        at clojure.core$reduce.invokeStatic(core.clj:6830)
        at clojure.core$reduce.invoke(core.clj:6812)
        at clojure.tools.deps.alpha$canonicalize_deps.invokeStatic(alpha.clj:362)
        at clojure.tools.deps.alpha$canonicalize_deps.invoke(alpha.clj:360)
        at clojure.tools.deps.alpha$resolve_deps.invokeStatic(alpha.clj:494)
        at clojure.tools.deps.alpha$resolve_deps.invoke(alpha.clj:475)
        at clojure.tools.deps.alpha$calc_basis.invokeStatic(alpha.clj:655)
        at clojure.tools.deps.alpha$calc_basis.invoke(alpha.clj:629)
        at clojure.tools.deps.alpha.script.make_classpath2$run_core.invokeStatic(make_classpath2.clj:91)
        at clojure.tools.deps.alpha.script.make_classpath2$run_core.invoke(make_classpath2.clj:57)
        at clojure.tools.deps.alpha.script.make_classpath2$run.invokeStatic(make_classpath2.clj:119)
        at clojure.tools.deps.alpha.script.make_classpath2$run.invoke(make_classpath2.clj:113)
        at clojure.tools.deps.alpha.script.make_classpath2$_main.invokeStatic(make_classpath2.clj:169)
        at clojure.tools.deps.alpha.script.make_classpath2$_main.doInvoke(make_classpath2.clj:140)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.main$main_opt.invokeStatic(main.clj:514)
        at clojure.main$main_opt.invoke(main.clj:510)
        at clojure.main$main.invokeStatic(main.clj:664)
        at clojure.main$main.doInvoke(main.clj:616)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.main.main(main.java:40)
~ $ clj -Sdeps '{:deps {org.clojure/clojurescript {:mvn/version \"RELEASE\"}}}' -M -m cljs.repl.node
Downloading: org/clojure/clojurescript/maven-metadata.xml from central
Downloading: org/clojure/clojurescript/1.10.844/clojurescript-1.10.844.pom from central
Downloading: com/google/javascript/closure-compiler-unshaded/v20210202/closure-compiler-unshaded-v20210202.pom from central
Downloading: com/cognitect/transit-clj/0.8.309/transit-clj-0.8.309.pom from central
Downloading: org/clojure/google-closure-library/0.0-20201211-3e6c510d/google-closure-library-0.0-20201211-3e6c510d.pom from central
Downloading: com/google/javascript/closure-compiler-main/v20210202/closure-compiler-main-v20210202.pom from central
Downloading: com/google/javascript/closure-compiler-parent/v20210202/closure-compiler-parent-v20210202.pom from central
Downloading: org/clojure/google-closure-library-third-party/0.0-20201211-3e6c510d/google-closure-library-third-party-0.0-20201211-3e6c510d.pom from central
Downloading: com/cognitect/transit-java/0.8.332/transit-java-0.8.332.pom from central
Downloading: org/clojure/google-closure-library/0.0-20201211-3e6c510d/google-closure-library-0.0-20201211-3e6c510d.jar from central
Downloading: commons-codec/commons-codec/1.10/commons-codec-1.10.jar from central
Downloading: org/clojure/clojurescript/1.10.844/clojurescript-1.10.844.jar from central
Downloading: com/cognitect/transit-clj/0.8.309/transit-clj-0.8.309.jar from central
Downloading: com/cognitect/transit-java/0.8.332/transit-java-0.8.332.jar from central
Downloading: org/clojure/google-closure-library-third-party/0.0-20201211-3e6c510d/google-closure-library-third-party-0.0-20201211-3e6c510d.jar from central
Downloading: com/google/javascript/closure-compiler-unshaded/v20210202/closure-compiler-unshaded-v20210202.jar from central
ClojureScript 1.10.844
cljs.user=>
```

**Comment by raspasov** [comment]
Apologies, I haven't dealt with Windows for ~10 years. If there's a magic fix, I would be happy to change the command.
